project:
  type: book
  output-dir: docs

book:
  title: "The Potato-Peel Cookbook"
  subtitle: "No ads, no stories, just recipes"
  author: "Casey Jelsema"
  date: "9/7/2025"
  favicon: images/general/ppcb_logo.png
  chapters:
    - index.qmd
    - substitutions.qmd
    - part: "Breakfast Batters"
      chapters:
        - chapters/breakfast-batter/dutch-baby.qmd
        - chapters/breakfast-batter/french-toast.qmd
        - chapters/breakfast-batter/pancakes.qmd
        - chapters/breakfast-batter/waffles.qmd
    - part: "Breakfast Other"
      chapters:
        - chapters/breakfast-other/bacon-sandwich.qmd
        - chapters/breakfast-other/breakfast-scramble.qmd
        - chapters/breakfast-other/cinnamon-roll-biscuits.qmd
        - chapters/breakfast-other/huevos-rancheros.qmd
        - chapters/breakfast-other/quiche.qmd
    - part: "Breakfast Sides"
      chapters:
        - chapters/breakfast-sides/biscuits.qmd
        - chapters/breakfast-sides/home-fries.qmd
        - chapters/breakfast-sides/sausage-gravy.qmd
format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    # toc: true
    # toc-depth: 2 # Includes levels #, ##
    # toc-expand: 2
    # toc-location: left
  # pdf:
  #   documentclass: scrreprt

knitr:
  opts_chunk: 
    echo: false
    warning: false
    message: false

editor: source

