project:
  type: book

book:
  title: "The Potato-Peel Cookbook"
  subtitle: "No ads, no stories, just recipes"
  author: "Casey Jelsema"
  date: "9/7/2025"
  chapters:
    - index.qmd
    - substitutions.qmd
    - intro.qmd

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
  pdf:
    documentclass: scrreprt

knitr:
  opts_chunk: 
    echo: false
    warning: false
    message: false

editor: source

