project:
  type: book
  output-dir: docs

book:
  title: "The Potato-Peel Cookbook"
  subtitle: "No ads, no stories, just recipes"
  author: "Casey Jelsema"
  date: "9/7/2025"
  favicon: _images/general/ppcb_logo.png
  chapters:
    - index.qmd
    - substitutions.qmd
    - part: "Breakfast Batters"
      chapters:
        - _chapters/breakfast-batter/dutch_baby.qmd
        - _chapters/breakfast-batter/french_toast.qmd
        - _chapters/breakfast-batter/pancakes.qmd
        - _chapters/breakfast-batter/waffles.qmd
    - part: "Breakfast Other"
      chapters:
        - _chapters/breakfast-other/bacon_sandwich.qmd
        - _chapters/breakfast-other/cinnamon_roll_biscuits.qmd
        - _chapters/breakfast-other/huevos_rancheros.qmd
format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    # toc: true
    # toc-depth: 2 # Includes levels #, ##
    # toc-expand: 2
    # toc-location: left
  # pdf:
  #   documentclass: scrreprt

knitr:
  opts_chunk: 
    echo: false
    warning: false
    message: false

editor: source

