# Substitutions {.unnumbered}


Pretty much all of the recipes need to avoid several allergens due to a household need. In particular dairy, soy, and eggs. 
Below I list some common items and substitutions that I use.



## Milk

Pretty much any alternative milk works. 
I tend to use oat milk, and have also used almond milk. 
Coconut milk tends to be a bit sweeter, so I try to avoid that. 

One thing to watch out for is that many of the alternative milks are sweetened or flavored with vanilla. That can throw off some of the recipes (especially the gravy). So if you're using this, make sure to get unsweetened and unflavored.


## Butter

Plenty of alternative butters exist.

- Stick butter: 
  - Earth Balance has a 1:1 substitute.
- Spreadable butter
  - Earth Balance has a 1:1 substitute.

## Eggs

Apparently aquafaba (the liquid that chickpeas come in) can be used as an egg white substitute. I haven't tried that as yet.

- For things that need whipped eggs (think: quiche, scrambled eggs, etc), the [JUST Egg](https://www.ju.st/eat/eggs) liquid is a good replacement.
- For baking, there are some powders that you mix in, such as 
[Bob's Red Mill Egg Replacer](https://www.bobsredmill.com/product/gluten-free-vegan-egg-replacer). These work in some cases, but don't seem to have the same binding power. This leads to me getting mad when I make waffles.



## Other Ingredients

- Heavy cream
  - Use full-fat coconut milk. This usually comes in a can. 
  - There's also one by Califa that has worked quite well.

- Buttermilk
  - Mix 1 cup of a milk alternative with 1-2 tablespoons of apple cider vinegar.

- Sugar
  - Lakanto makes a 1:1 sugar substitute using monkfruit.
  - Lakanto also makes a 1:1 powdered sugar replacement (also using monkfruit)
  - Coconut sugar can be used to replace brown sugar.
  - Sugar substitudes should only be used when you need the sweetness.
    If you're making something with yeast, I don't think the monkfruit sugar will be useful. I haven't tried carmalizing the monkfruit sugar, but I'm guessing it wouldn't work.






