# Chapter Title


```{r}
#| label: setup-chapter
#| results: false
#| output: false


library("tidyverse")
library("tinytable")



tlwd <- 0.125
bgcol <- "grey60"
bgcol <- "skyblue4"



```



## Dish Name



**Source:** I don’t remember.


**Ingredients:**


```{r}
#| label: recipie-name

dat <- tibble(
  Ingredients = c(
    "Item 1"
  ),
  Tools = c(
    "Item 1"
  )
)


dat |> 
  tt(  theme = "striped" ) |> 
  style_tt( i=0, background=bgcol, color="white") |> 
  style_tt( i=4, j=2, background=bgcol, color="white", bold=TRUE )
  # style_tt( i=0, line = "t", line_color="black", line_width = tlwd) |> 
  # style_tt( i=1, line = "t", line_color="black", line_width = tlwd) |> 
  # style_tt( i=8, line = "b", line_color="black", line_width = tlwd) |> 
  # style_tt( i=4, j=2, line = "t", line_color="black", line_width = tlwd )  |> 
  # style_tt( i=4, j=2, line = "b", line_color="black", line_width = tlwd )  |> 


```



**Directions:**


**Variations:**



**Notes:**

- Nothing yet.










