# Breakfast

```{r}
#| label: setup-breakfast
#| results: false
#| output: false


library("tidyverse")
library("tinytable")



tlwd <- 0.125
bgcol <- "grey60"
bgcol <- "skyblue4"



```



## Dutch Baby

A Dutch baby is kind of a weird hybrid between a pancake and french toast, maybe. I like it, though I prefer waffles or french toast.


**Source:** I don’t remember.


**Ingredients:**


```{r}
#| label: dutch-baby

dat <- tibble(
  Ingredients = c(
    "1/2 cup flour",
    "1/2 cup milk",
    "3 eggs",
    "1-2 tbsp sugar",
    "4 tbsp butter",
    "1/2 - 1 tsp vanilla extract",
    "1/2 tsp salt",
    "1 tsp cinnamon"
  ),
  Tools = c(
    "Cast iron skillet",
    "Mixing bowl",
    "Whisk",
    "Topping",
    "Powdered sugar",
    "Syrup (maple)",
    "Fried chicken",
    "Fruit"
  )
)


dat |> 
  tt(  theme = "striped" ) |> 
  style_tt( i=0, background=bgcol, color="white") |> 
  style_tt( i=4, j=2, background=bgcol, color="white", bold=TRUE )
  # style_tt( i=0, line = "t", line_color="black", line_width = tlwd) |> 
  # style_tt( i=1, line = "t", line_color="black", line_width = tlwd) |> 
  # style_tt( i=8, line = "b", line_color="black", line_width = tlwd) |> 
  # style_tt( i=4, j=2, line = "t", line_color="black", line_width = tlwd )  |> 
  # style_tt( i=4, j=2, line = "b", line_color="black", line_width = tlwd )  |> 


```



**Directions:**


**Variations:**



**Notes:**


